spring.application.name=user-service

spring.datasource.url=jdbc:mysql://localhost:3306/paypal
spring.datasource.username=root
spring.datasource.password=pr4n4v
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
